In [30]:
import pandas as pd

df_labels = pd.read_csv("dataset_labels.csv")
df_labels

,file_path,filename,is_doc_id,id_doc_type,doc_type
0,dataset/false_doc,12031810-405818722.jpg,False,NaN,NaN
1,dataset/false_doc,facture-d-avoir-exemple-744x1024-2687424784.jpg,False,NaN,NaN
2,dataset/false_id,1-18900169.jpg,False,NaN,NaN
3,dataset/false_id,1-842369233.jpg,False,NaN,NaN
4,dataset/false_id,Document-d-identite-2.jpg,False,NaN,NaN
5,dataset/false_id,ID_passport_USA-2021-497107151.jpg,False,NaN,NaN
6,dataset/false_id,IMG_6211_LegalPhoto-1697863245.jpg,False,NaN,NaN
7,dataset/false_id,carte-d-identite-ce-qui-change-en-bretagne_317...,False,NaN,NaN
8,dataset/false_id,csm_CA_RPC_2021_1920_4c0a2d9287-515808575.jpg,False,NaN,NaN
9,dataset/false_id,les-faux-papiers-ne-sont-pas-toujours-facileme...,False,NaN,NaN
10,dataset/false_id,vias-pages-3783188661.jpg,False,NaN,NaN
11,dataset/id_cards,0b43b0c-frenchID-3907357441.jpg,True,id card,id card
12,dataset/id_cards,1-2471433401.jpg,True,id card,id card
13,dataset/id_cards,1-3118488783.jpg,True,id card,id card
14,dataset/id_cards,1-4014550170.jpg,True,id card,id card
15,dataset/id_cards,21-french-identity-card-1988-1994-PCBNWG-36448...,True,id card,id card
16,dataset/id_cards,66e4b41eacf401726264350-445115958.jpg,True,id card,id card
17,dataset/id_cards,big-picture-id-photo-2017-06-20-01-1282880992.jpg,True,id card,id card
18,dataset/id_cards,depositphotos_5111236-French-national-identity...,True,id card,id card
19,dataset/id_cards,fnic-jpg-1994132894.jpg,True,id card,id card
20,dataset/id_cards,french-id-card-real-french-id-card-french-iden...,True,id card,id card
21,dataset/jdd,1-1822160908.jpg,False,NaN,jdd
22,dataset/jdd,1689160419-3971040533.jpg,False,NaN,jdd
23,dataset/jdd,1719685377-1436965417.jpg,False,NaN,jdd
24,dataset/jdd,exemple-de-justificatif-de-domicile-3015945657...,False,NaN,jdd
25,dataset/jdd,facture-EDF-page-1-1270172759.jpg,False,NaN,jdd
26,dataset/passports,1683728325-20230510-new-passport-canada-4-3997...,True,passport,passport
27,dataset/passports,196079-3573231712.jpg,True,passport,passport
28,dataset/passports,DelpEphraim_Passport-001-4263437215.jpg,True,passport,passport
29,dataset/passports,Ecp5OYUWAAAdVec-2854078686.jpg,True,passport,passport
30,dataset/passports,Standard-passport-2638612431.jpg,True,passport,passport
31,dataset/passports,french-diplomatic-passport-v0-0xptroj0uxia1-10...,True,passport,passport
32,dataset/passports,passeport-controle-4-3813735177.jpg,True,passport,passport
33,dataset/passports,passport-1-1721243253.jpg,True,passport,passport
34,dataset/false_doc,Voorbeeld-factuur-FR-1950745723.png,False,NaN,NaN
35,dataset/false_doc,facture-proforma-1025995893.png,False,NaN,NaN
36,dataset/id_cards,France-ID-Card-front-1-4214685582.png,True,id card,id card
37,dataset/passports,France-pass-1-3091894550.png,True,passport,passport
38,dataset/passports,_133028110_passport_dates_2x640-nc-2868492495.png,True,passport,passport
39,dataset/passports,public-3423989802.png,True,passport,passport
40,dataset/false_doc,Bulletin_de_souscription_CORUM_LEpargne_CC_Vic...,False,NaN,NaN
41,dataset/false_doc,Questionnaire_de_connaissance_client_Victor_Co...,False,NaN,NaN
42,dataset/jdd,atteestation-domicile-3208283458.pdf,False,NaN,jdd

In [31]:
df_results = pd.read_csv("results.csv")
df_results

,file_path,filename,mistral_is_doc_id,mistral_id_doc_type,mistral_doc_type,azure_is_doc_id,azure_id_doc_type,azure_doc_type,mistral_vision_is_doc_id,mistral_vision_id_doc_type,mistral_vision_doc_type,azure_vision_is_doc_id,azure_vision_id_doc_type,azure_vision_doc_type,aligned
0,dataset/false_doc,12031810-405818722.jpg,True,proof_of_residency,letter,NaN,NaN,NaN,True,proof_of_residency,official_request_for_vehicle_registration_docu...,False,not_identity_doc,official request letter,False
1,dataset/false_doc,facture-d-avoir-exemple-744x1024-2687424784.jpg,False,not_identity_doc,credit_note,NaN,NaN,NaN,False,not_identity_doc,credit_note,False,not_identity_doc,credit note,False
2,dataset/false_id,1-18900169.jpg,True,id card,identity card,NaN,NaN,NaN,True,id_card,"[{'type': 'student_id', 'issuer': 'Université ...",True,id card,"student_id_card, voter_id_card",False
3,dataset/false_id,1-842369233.jpg,True,proof_of_residency,residence_permit,NaN,NaN,NaN,True,proof_of_residency,Titre de Séjour (French Residence Permit),True,proof_of_residency,titre de séjour,False
4,dataset/false_id,Document-d-identite-2.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,travel_document,True,passport,passport,False
5,dataset/false_id,ID_passport_USA-2021-497107151.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,government_issued_travel_document,True,passport,passport,False
6,dataset/false_id,IMG_6211_LegalPhoto-1697863245.jpg,True,id card,identity photo,NaN,NaN,NaN,True,id card,Legal identity photo printout conforming to IS...,True,not_identity_doc,passport photo sheet,False
7,dataset/false_id,carte-d-identite-ce-qui-change-en-bretagne_317...,True,id card,identity document,NaN,NaN,NaN,True,id_card,Carte Nationale d’Identité (French National Id...,True,id card,French national identity card,False
8,dataset/false_id,csm_CA_RPC_2021_1920_4c0a2d9287-515808575.jpg,True,proof_of_residency,permanent_resident_card,NaN,NaN,NaN,True,id card,Permanent Resident Card,True,proof_of_residency,permanent resident card,False
9,dataset/false_id,les-faux-papiers-ne-sont-pas-toujours-facileme...,True,id card,identity card,NaN,NaN,NaN,True,id_card,{'primary': ['Italian Identity Card (Carta d’I...,True,passport,"passport, id card, driving license",False
10,dataset/false_id,vias-pages-3783188661.jpg,False,not_identity_doc,station_record,NaN,NaN,NaN,True,passport,travel_document,True,passport,passport,False
11,dataset/id_cards,0b43b0c-frenchID-3907357441.jpg,True,id card,identity card,NaN,NaN,NaN,True,id card,Carte Nationale d’Identité (French National Id...,True,id card,identity card,False
12,dataset/id_cards,1-2471433401.jpg,True,id card,national identity card,NaN,NaN,NaN,True,id_card,Carte Nationale d'Identité (Moroccan National ...,True,id card,national identity card,False
13,dataset/id_cards,1-3118488783.jpg,True,id card,identity card,NaN,NaN,NaN,True,id_card,French National Identity Card (Carte Nationale...,True,id card,French national identity card,False
14,dataset/id_cards,1-4014550170.jpg,True,id card,national identity card,NaN,NaN,NaN,True,id_card,Carte Nationale d'Identité (French National Id...,True,id card,French national identity card,False
15,dataset/id_cards,21-french-identity-card-1988-1994-PCBNWG-36448...,True,id card,national identity card,NaN,NaN,NaN,True,id card,Carte Nationale d'Identité (French National Id...,True,id card,French national identity card,False
16,dataset/id_cards,66e4b41eacf401726264350-445115958.jpg,True,id card,identity card,NaN,NaN,NaN,True,id_card,French National Identity Card (Carte Nationale...,True,id card,French national identity card,False
17,dataset/id_cards,big-picture-id-photo-2017-06-20-01-1282880992.jpg,True,id card,national identity card,NaN,NaN,NaN,True,id_card,Carte Nationale d'Identité (French National Id...,True,id card,French national identity card,False
18,dataset/id_cards,depositphotos_5111236-French-national-identity...,True,id card,national identity card,NaN,NaN,NaN,True,id_card,Carte Nationale d’Identité (French National Id...,True,id card,French national identity card,False
19,dataset/id_cards,fnic-jpg-1994132894.jpg,True,id card,identity card,NaN,NaN,NaN,True,id_card,French National Identity Card (Carte Nationale...,True,id card,French national identity card,False
20,dataset/id_cards,french-id-card-real-french-id-card-french-iden...,True,id card,national identity card,NaN,NaN,NaN,True,id_card,French National Identity Card (Carte Nationale...,True,id card,French national identity card,False
21,dataset/jdd,1-1822160908.jpg,False,not_identity_doc,telephone_bill,NaN,NaN,NaN,False,not_identity_doc,telecommunications_bill,False,not_identity_doc,utility_bill,False
22,dataset/jdd,1689160419-3971040533.jpg,False,not_identity_doc,invoice,NaN,NaN,NaN,False,not_identity_doc,rental_arrears_notice,False,not_identity_doc,rent invoice,False
23,dataset/jdd,1719685377-1436965417.jpg,False,not_identity_doc,utility_bill,NaN,NaN,NaN,False,not_identity_doc,attestation_titulaire_de_contrat,False,not_identity_doc,attestation de contrat EDF,False
24,dataset/jdd,exemple-de-justificatif-de-domicile-3015945657...,False,not_identity_doc,utility_bill,NaN,NaN,NaN,False,not_identity_doc,electricity_bill,False,not_identity_doc,electricity bill,False
25,dataset/jdd,facture-EDF-page-1-1270172759.jpg,False,not_identity_doc,utility_bill,NaN,NaN,NaN,False,not_identity_doc,utility_bill,False,not_identity_doc,utility_bill,False
26,dataset/passports,1683728325-20230510-new-passport-canada-4-3997...,True,passport,passport,NaN,NaN,NaN,True,passport,government_issued_travel_document,True,passport,Canadian passport,False
27,dataset/passports,196079-3573231712.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,government_issued_passport,True,passport,passport,False
28,dataset/passports,DelpEphraim_Passport-001-4263437215.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,United States of America Passport,True,passport,United States passport,False
29,dataset/passports,Ecp5OYUWAAAdVec-2854078686.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,Indian Passport,True,passport,Indian Passport,False
30,dataset/passports,Standard-passport-2638612431.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,United Kingdom Passport (Specimen),True,passport,UK passport,False
31,dataset/passports,french-diplomatic-passport-v0-0xptroj0uxia1-10...,True,passport,diplomatic passport,NaN,NaN,NaN,True,passport,Diplomatic Passport,True,passport,diplomatic passport,False
32,dataset/passports,passeport-controle-4-3813735177.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,government_issued_travel_document,True,passport,passport,False
33,dataset/passports,passport-1-1721243253.jpg,True,passport,passport,NaN,NaN,NaN,True,passport,Republic of Eolie Passport,True,passport,passport,False
34,dataset/false_doc,Voorbeeld-factuur-FR-1950745723.png,False,not_identity_doc,invoice,NaN,NaN,NaN,False,not_identity_doc,invoice,False,not_identity_doc,invoice,False
35,dataset/false_doc,facture-proforma-1025995893.png,False,not_identity_doc,invoice,NaN,NaN,NaN,False,not_identity_doc,proforma_invoice,False,not_identity_doc,invoice,False
36,dataset/id_cards,France-ID-Card-front-1-4214685582.png,True,id card,identity card,NaN,NaN,NaN,True,id_card,French National Identity Card (Carte Nationale...,True,id card,French National Identity Card,False
37,dataset/passports,France-pass-1-3091894550.png,True,passport,passport,NaN,NaN,NaN,True,passport,government_issued_travel_document,True,passport,French passport,False
38,dataset/passports,_133028110_passport_dates_2x640-nc-2868492495.png,True,passport,passport,NaN,NaN,NaN,True,passport,UK_Specimen_Passport,True,passport,passport,False
39,dataset/passports,public-3423989802.png,True,passport,passport,NaN,NaN,NaN,True,passport,French Republic Passport,True,passport,French passport,False

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve

MODELS = {
    "Mistral OCR":    "mistral_is_doc_id",
    "Azure CU":       "azure_is_doc_id",
    "Mistral Vision": "mistral_vision_is_doc_id",
    "Azure Vision":   "azure_vision_is_doc_id",
}
BOOL_MAP = {True: 1, False: 0, "True": 1, "False": 0}

# Merge ground truth with model results on filename
merged = df_labels[["filename", "is_doc_id"]].merge(df_results, on="filename", suffixes=("_gt", ""))
merged = merged.dropna(subset=["is_doc_id"])


def get_yt_ys(col):
    """Return (y_true, y_score) for a given model column, excluding missing predictions."""
    mask = merged[col].notna() & (merged[col] != "")
    y_t = merged.loc[mask, "is_doc_id"].astype(bool).astype(int)
    y_s = merged.loc[mask, col].map(BOOL_MAP).fillna(0).astype(int)
    return y_t, y_s


fig, ax = plt.subplots(figsize=(7, 6))
ax.plot([0, 1], [0, 1], "k--", lw=1, label="Random (AUC = 0.50)")

for name, col in MODELS.items():
    y_t, y_s = get_yt_ys(col)
    if len(y_t) == 0 or y_t.nunique() < 2:
        print(f"[skip] {name}: not enough data (n={len(y_t)})")
        continue
    auc = roc_auc_score(y_t, y_s)
    fpr, tpr, _ = roc_curve(y_t, y_s)
    ax.plot(fpr, tpr, marker="o", label=f"{name} (AUC = {auc:.2f}, n={len(y_t)})")

ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC — is_doc_id classification")
ax.legend(loc="lower right")
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score

rows = []
for name, col in MODELS.items():
    y_t, y_s = get_yt_ys(col)
    if len(y_t) == 0 or y_t.nunique() < 2:
        continue
    rows.append({
        "model":     name,
        "n":         len(y_t),
        "accuracy":  accuracy_score(y_t, y_s),
        "precision": precision_score(y_t, y_s, zero_division=0),
        "recall":    recall_score(y_t, y_s, zero_division=0),
        "f1":        f1_score(y_t, y_s, zero_division=0),
        "mcc":       matthews_corrcoef(y_t, y_s),
        "auc":       roc_auc_score(y_t, y_s),
    })

(pd.DataFrame(rows)
   .set_index("model")
   .style
   .format("{:.2f}", subset=["accuracy", "precision", "recall", "f1", "mcc", "auc"])
   .background_gradient(cmap="RdYlGn", subset=["accuracy", "precision", "recall", "f1", "mcc", "auc"])
)

## Conclusion — Performance des modèles sur `is_doc_id`

L'analyse porte sur **40 fichiers** labellisés (19 documents d'identité, 21 non-identité), évalués sur trois modèles disposant de résultats complets (Azure CU n'a produit aucune prédiction et est exclu).

### Résultats

| Modèle | Accuracy | Precision | Recall | F1 | MCC | AUC |
|---|---|---|---|---|---|---|
| Mistral OCR | 0.78 | 0.71 | **1.00** | 0.83 | 0.60 | 0.75 |
| Mistral Vision | 0.75 | 0.69 | **1.00** | 0.81 | 0.55 | 0.72 |
| Azure Vision | 0.78 | 0.71 | **1.00** | 0.83 | 0.60 | 0.75 |

### Points clés

**Recall parfait (1.00) pour les trois modèles** — aucun document d'identité réel n'est manqué. C'est la propriété la plus critique dans un contexte de vérification documentaire : un faux négatif (document d'identité non détecté) serait une erreur grave.

**Precision modérée (~0.70)** — environ 30 % des documents classifiés comme "identité" ne le sont pas. Ces faux positifs proviennent principalement de la catégorie `false_id` (photos de documents, coupures de presse sur les cartes d'identité) que les modèles confondent avec de vrais documents.

**MCC entre 0.55 et 0.60** — performance correcte mais perfectible sur un dataset déséquilibré. Un MCC > 0.8 serait souhaitable en production.

**Mistral OCR et Azure Vision à égalité** (F1 = 0.83, MCC = 0.60) devant Mistral Vision (F1 = 0.81, MCC = 0.55). L'approche OCR n'apporte pas d'avantage décisif sur la vision pure.

### Limites de l'analyse

- **Dataset petit** (n=40 avec labels) — les métriques sont sensibles à quelques exemples.
- **Azure CU non évalué** — absence de résultats dans `results.csv`, à relancer.
- **Catégorie `false_id` difficile** — images de documents sur Internet (pas de vrais faux) : la tâche est plus ambiguë que des cas réels.

### Recommandation

Pour un usage production, **augmenter le dataset** (notamment les faux positifs) et **affiner le seuil de décision** sur `id_doc_type` pour réduire la precision sans dégrader le recall.